---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBJfdmjHIu5oPanOV9/ERehOhrisWI0SWLrwmuIepLzquU9IyiyRzFVRFFJ6NvSxeBQYduABdwdFkXUyKxxUPyKlM/DlNFbKF9V6mEXPV2NiJs4Ov2yD+eT96+ruGwDv0Wu+/Kifw00P8WmQDbsKyBX9T6Pgj7nFZbghs06vOoF5/6PhJU2nM5UcU4yZyVJ+O4eyDxF4omE8XrcvzeUrbGw2ttQK/4UQPX5MPfYmEpXTZ3ORZC0jUIbQ+gNBNwYIFOTuDaXrp5Uk7XyBw6BDWp7GcD51eAC3uEoRTxh6QN3q83SEOytyQp9wRz3OefyIJZEeti4bkS1Riz1oriy7ziRsxIPaFGoL63M+1UToAmwm+tBbIKRo6Gl8Gueb4jY5LJKfraJWi4uicTSEvopa/QKHPLpeT+PIlSemFjgGxI7prelhRREO8T9KuN/qbG5Y8yq62kEMIVICMCkkMreAJT8DDumAsP7cnbDb5JtRQqWFzchvJuVBv2/zxtMvS4KF096YlLuHPNFjAez905hUQEj5aBIytEq/m8M0kuSUJA8Dvm4/kCR8teYFtQJgjFbGT3lC75DrYjEIGS0RNMvCn0XUq6HPMDbR8eHHqVcOq/lWlWqRkYA0cQMnGaA89Cnvam119NYo+KzB1HLN/Cunc50apdkV9/wsyv4i35I4LMIWcahm5whnKrTHFVIVb/IgVfbKuaE2Cq92jWosHyaSgeqRw==
    SECRET_KEY: AgBe2gn6ux2CaxriSN02Gt8DTraSTkpIfGGO+W51PAOJvkBDBRNz9s5czGp8CNx+oPaLAogQOHPhHw9mNajT7YeUPA9qw6O0ZQRej1JM8sFAW4Z4py3IuSPWrQR4XsDo6ErsS9w93ZozdbiplDHQwdhHxTDXt9GbzaoyCjbB2/Cfvmfnf6ihHxTUiGJtds9NOFbOAuRn3QWEZLfdp9JM7gVeb2UcjVlRaHm2UB7qeGOMNJ1cOKKf4c48uC/DcYQCXVXtMHRY6KXt053jI8ledEFC4hjNn8NVtP2uop7EP0hvTnBEDYj/YzpLoyL/mn2ErOwNQtN+SRcshMjqNmvH5kr+P/A9OZG51d3Kl0ITYwjUBG65L7fnw8etzy4dF9h/ELDuea24rKwARItXYhzLIBujQ/4PDIf1BtyaIjVKn2Fy1r7F6/yiqAwz5jppVC9nnF8aS5dn8pS2Ak5VlrSH1IXWJWuux5xsrITB6il5nZy9r4mCjYjpWpEni31gPPV50ZZKQu3cQ92M9Q6vgtbaQ2JaJdapdAoja3/jOyo4rEMYvm63ELaHiEbIxqRr+axaZqTJ0uL4pu1Yy/H+CzdN8LzVfcAFXLTQIZBBMvx6vPwqnYxOIlBW5SuzfylUJFEKlE/4cdog6krqK7UXIxpqe+n6PHpsEayGJSSI6CudCm7RRb7BBbQF9NzJ0YHR3W0XkQ9QXX0LbWETbItCyVErFo+px3S3qIqjRpoMoed9z4gzt8yyUvUyK2PBHw==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: default
    type: Opaque
