# Generated by ChatGPT, tested/tweaked by @robert-todora

# Install Java
Write-Output "Installing Java..."
$javaInstallerUrl = "https://javadl.oracle.com/webapps/download/AutoDL?BundleId=247827_de09f66f5a4d4b5bbb5ed0d23b8330c8"
$javaInstallerPath = "$env:TEMP\jdk-installer.exe"
Invoke-WebRequest -Uri $javaInstallerUrl -OutFile $javaInstallerPath
Start-Process -FilePath $javaInstallerPath -ArgumentList "/s" -Wait

# Refresh environment variables to include Java
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")

# Check Java installation
Write-Output "Checking Java installation..."
java -version
if ($?) {
    Write-Output "Java installation successful."
} else {
    Write-Error "Java installation failed."
    exit 1
}

# Install Android Studio
Write-Output "Installing Android Studio..."
$androidStudioInstallerUrl = "https://redirector.gvt1.com/edgedl/android/studio/install/2023.3.1.19/android-studio-2023.3.1.19-windows.exe"
$androidStudioInstallerPath = "$env:TEMP\android-studio-installer.exe"
Invoke-WebRequest -Uri $androidStudioInstallerUrl -OutFile $androidStudioInstallerPath
Start-Process -FilePath $androidStudioInstallerPath -ArgumentList "/S" -Wait

# Check Android Studio installation
Write-Output "Checking Android Studio installation..."
$androidStudioPath = "C:\Program Files\Android\Android Studio\bin\studio64.exe"
if (Test-Path $androidStudioPath) {
    Write-Output "Android Studio installation successful."
} else {
    Write-Error "Android Studio installation failed."
    exit 1
}

Write-Output "Installation complete. Please restart your terminal or run 'refreshenv' to update the environment variables."
